// Figma Text & Typography - Seed Data
const SEED_DATA_VERSION = 1;

// ============================================================
// Font Collections
// ============================================================

const FONT_FAMILIES = [
    { id: 'ff_001', name: 'Inter', category: 'sans-serif', source: 'google', isVariable: true, variableAxes: [{ tag: 'wght', name: 'Weight', min: 100, max: 900, default: 400 }, { tag: 'slnt', name: 'Slant', min: -10, max: 0, default: 0 }], styles: ['Thin', 'Extra Light', 'Light', 'Regular', 'Medium', 'Semi Bold', 'Bold', 'Extra Bold', 'Black'], openTypeFeatures: ['liga', 'calt', 'ss01', 'ss02', 'ss03', 'cv01', 'cv02', 'cv05', 'cv11', 'zero', 'frac', 'ordn', 'sups', 'subs', 'kern'], popular: true },
    { id: 'ff_002', name: 'Roboto', category: 'sans-serif', source: 'google', isVariable: true, variableAxes: [{ tag: 'wght', name: 'Weight', min: 100, max: 900, default: 400 }, { tag: 'wdth', name: 'Width', min: 75, max: 100, default: 100 }], styles: ['Thin', 'Light', 'Regular', 'Medium', 'Bold', 'Black'], openTypeFeatures: ['liga', 'calt', 'kern', 'frac', 'sups', 'subs', 'zero'], popular: true },
    { id: 'ff_003', name: 'Open Sans', category: 'sans-serif', source: 'google', isVariable: true, variableAxes: [{ tag: 'wght', name: 'Weight', min: 300, max: 800, default: 400 }], styles: ['Light', 'Regular', 'Medium', 'Semi Bold', 'Bold', 'Extra Bold'], openTypeFeatures: ['liga', 'kern', 'frac', 'sups', 'subs'], popular: true },
    { id: 'ff_004', name: 'Lato', category: 'sans-serif', source: 'google', isVariable: false, styles: ['Thin', 'Light', 'Regular', 'Bold', 'Black'], openTypeFeatures: ['liga', 'kern'], popular: true },
    { id: 'ff_005', name: 'Montserrat', category: 'sans-serif', source: 'google', isVariable: true, variableAxes: [{ tag: 'wght', name: 'Weight', min: 100, max: 900, default: 400 }, { tag: 'ital', name: 'Italic', min: 0, max: 1, default: 0 }], styles: ['Thin', 'Extra Light', 'Light', 'Regular', 'Medium', 'Semi Bold', 'Bold', 'Extra Bold', 'Black'], openTypeFeatures: ['liga', 'calt', 'kern', 'frac', 'ss01'], popular: true },
    { id: 'ff_006', name: 'Poppins', category: 'sans-serif', source: 'google', isVariable: false, styles: ['Thin', 'Extra Light', 'Light', 'Regular', 'Medium', 'Semi Bold', 'Bold', 'Extra Bold', 'Black'], openTypeFeatures: ['liga', 'kern'], popular: true },
    { id: 'ff_007', name: 'Playfair Display', category: 'serif', source: 'google', isVariable: true, variableAxes: [{ tag: 'wght', name: 'Weight', min: 400, max: 900, default: 400 }], styles: ['Regular', 'Medium', 'Semi Bold', 'Bold', 'Extra Bold', 'Black'], openTypeFeatures: ['liga', 'calt', 'kern', 'ss01', 'ss02', 'smcp', 'onum', 'lnum'], popular: true },
    { id: 'ff_008', name: 'Merriweather', category: 'serif', source: 'google', isVariable: false, styles: ['Light', 'Regular', 'Bold', 'Black'], openTypeFeatures: ['liga', 'kern', 'onum', 'lnum'], popular: false },
    { id: 'ff_009', name: 'Source Code Pro', category: 'monospace', source: 'google', isVariable: true, variableAxes: [{ tag: 'wght', name: 'Weight', min: 200, max: 900, default: 400 }], styles: ['Extra Light', 'Light', 'Regular', 'Medium', 'Semi Bold', 'Bold', 'Black'], openTypeFeatures: ['liga', 'calt', 'kern', 'zero', 'ss01', 'ss02'], popular: false },
    { id: 'ff_010', name: 'JetBrains Mono', category: 'monospace', source: 'google', isVariable: true, variableAxes: [{ tag: 'wght', name: 'Weight', min: 100, max: 800, default: 400 }], styles: ['Thin', 'Extra Light', 'Light', 'Regular', 'Medium', 'Semi Bold', 'Bold', 'Extra Bold'], openTypeFeatures: ['liga', 'calt', 'kern', 'zero', 'ss01', 'ss02', 'cv01', 'cv02', 'cv03', 'cv04', 'cv05', 'cv06', 'cv07', 'cv08', 'cv99'], popular: false },
    { id: 'ff_011', name: 'Noto Sans', category: 'sans-serif', source: 'google', isVariable: true, variableAxes: [{ tag: 'wght', name: 'Weight', min: 100, max: 900, default: 400 }, { tag: 'wdth', name: 'Width', min: 62.5, max: 100, default: 100 }], styles: ['Thin', 'Extra Light', 'Light', 'Regular', 'Medium', 'Semi Bold', 'Bold', 'Extra Bold', 'Black'], openTypeFeatures: ['liga', 'calt', 'kern'], popular: false },
    { id: 'ff_012', name: 'Noto Serif', category: 'serif', source: 'google', isVariable: true, variableAxes: [{ tag: 'wght', name: 'Weight', min: 100, max: 900, default: 400 }, { tag: 'wdth', name: 'Width', min: 62.5, max: 100, default: 100 }], styles: ['Thin', 'Extra Light', 'Light', 'Regular', 'Medium', 'Semi Bold', 'Bold', 'Extra Bold', 'Black'], openTypeFeatures: ['liga', 'calt', 'kern', 'smcp', 'onum', 'lnum'], popular: false },
    { id: 'ff_013', name: 'Noto Sans SC', category: 'sans-serif', source: 'google', isVariable: false, styles: ['Thin', 'Light', 'Regular', 'Medium', 'Bold', 'Black'], openTypeFeatures: ['liga', 'kern'], popular: false, language: 'Simplified Chinese' },
    { id: 'ff_014', name: 'Noto Sans TC', category: 'sans-serif', source: 'google', isVariable: false, styles: ['Thin', 'Light', 'Regular', 'Medium', 'Bold', 'Black'], openTypeFeatures: ['liga', 'kern'], popular: false, language: 'Traditional Chinese' },
    { id: 'ff_015', name: 'Noto Sans JP', category: 'sans-serif', source: 'google', isVariable: false, styles: ['Thin', 'Light', 'Regular', 'Medium', 'Bold', 'Black'], openTypeFeatures: ['liga', 'kern'], popular: false, language: 'Japanese' },
    { id: 'ff_016', name: 'Noto Sans KR', category: 'sans-serif', source: 'google', isVariable: false, styles: ['Thin', 'Light', 'Regular', 'Medium', 'Bold', 'Black'], openTypeFeatures: ['liga', 'kern'], popular: false, language: 'Korean' },
    { id: 'ff_017', name: 'Noto Sans Arabic', category: 'sans-serif', source: 'google', isVariable: true, variableAxes: [{ tag: 'wght', name: 'Weight', min: 100, max: 900, default: 400 }], styles: ['Thin', 'Light', 'Regular', 'Medium', 'Semi Bold', 'Bold', 'Black'], openTypeFeatures: ['liga', 'calt', 'kern'], popular: false, language: 'Arabic', rtl: true },
    { id: 'ff_018', name: 'Noto Sans Hebrew', category: 'sans-serif', source: 'google', isVariable: true, variableAxes: [{ tag: 'wght', name: 'Weight', min: 100, max: 900, default: 400 }], styles: ['Thin', 'Light', 'Regular', 'Medium', 'Semi Bold', 'Bold', 'Black'], openTypeFeatures: ['liga', 'calt', 'kern'], popular: false, language: 'Hebrew', rtl: true },
    { id: 'ff_019', name: 'Raleway', category: 'sans-serif', source: 'google', isVariable: true, variableAxes: [{ tag: 'wght', name: 'Weight', min: 100, max: 900, default: 400 }], styles: ['Thin', 'Extra Light', 'Light', 'Regular', 'Medium', 'Semi Bold', 'Bold', 'Extra Bold', 'Black'], openTypeFeatures: ['liga', 'kern', 'ss01', 'onum', 'lnum'], popular: false },
    { id: 'ff_020', name: 'Ubuntu', category: 'sans-serif', source: 'google', isVariable: false, styles: ['Light', 'Regular', 'Medium', 'Bold'], openTypeFeatures: ['liga', 'kern'], popular: false },
    { id: 'ff_021', name: 'PT Sans', category: 'sans-serif', source: 'google', isVariable: false, styles: ['Regular', 'Bold'], openTypeFeatures: ['liga', 'kern'], popular: false },
    { id: 'ff_022', name: 'Georgia', category: 'serif', source: 'installed', isVariable: false, styles: ['Regular', 'Bold'], openTypeFeatures: ['kern'], popular: false },
    { id: 'ff_023', name: 'Helvetica Neue', category: 'sans-serif', source: 'installed', isVariable: false, styles: ['Ultra Light', 'Thin', 'Light', 'Regular', 'Medium', 'Bold', 'Heavy', 'Black'], openTypeFeatures: ['liga', 'kern'], popular: false },
    { id: 'ff_024', name: 'Arial', category: 'sans-serif', source: 'installed', isVariable: false, styles: ['Regular', 'Bold', 'Black'], openTypeFeatures: ['kern'], popular: false },
    { id: 'ff_025', name: 'SF Pro', category: 'sans-serif', source: 'installed', isVariable: true, variableAxes: [{ tag: 'wght', name: 'Weight', min: 100, max: 900, default: 400 }, { tag: 'opsz', name: 'Optical Size', min: 6, max: 19, default: 12 }], styles: ['Ultra Light', 'Thin', 'Light', 'Regular', 'Medium', 'Semi Bold', 'Bold', 'Heavy', 'Black'], openTypeFeatures: ['liga', 'calt', 'kern', 'ss01', 'ss02', 'ss03', 'cv01', 'cv02'], popular: false },
    { id: 'ff_026', name: 'Fira Code', category: 'monospace', source: 'installed', isVariable: true, variableAxes: [{ tag: 'wght', name: 'Weight', min: 300, max: 700, default: 400 }], styles: ['Light', 'Regular', 'Medium', 'Semi Bold', 'Bold'], openTypeFeatures: ['liga', 'calt', 'kern', 'zero', 'ss01', 'ss02', 'ss03', 'ss04', 'ss05', 'cv01', 'cv02', 'cv14'], popular: false },
    { id: 'ff_027', name: 'DM Sans', category: 'sans-serif', source: 'google', isVariable: true, variableAxes: [{ tag: 'wght', name: 'Weight', min: 100, max: 1000, default: 400 }, { tag: 'opsz', name: 'Optical Size', min: 9, max: 40, default: 14 }], styles: ['Thin', 'Extra Light', 'Light', 'Regular', 'Medium', 'Semi Bold', 'Bold', 'Extra Bold', 'Black'], openTypeFeatures: ['liga', 'kern', 'ss01', 'ss03'], popular: false },
    { id: 'ff_028', name: 'Space Grotesk', category: 'sans-serif', source: 'google', isVariable: true, variableAxes: [{ tag: 'wght', name: 'Weight', min: 300, max: 700, default: 400 }], styles: ['Light', 'Regular', 'Medium', 'Semi Bold', 'Bold'], openTypeFeatures: ['liga', 'kern', 'ss01'], popular: false },
    { id: 'ff_029', name: 'IBM Plex Sans', category: 'sans-serif', source: 'google', isVariable: false, styles: ['Thin', 'Extra Light', 'Light', 'Regular', 'Medium', 'Semi Bold', 'Bold'], openTypeFeatures: ['liga', 'kern', 'frac', 'sups', 'subs', 'zero'], popular: false },
    { id: 'ff_030', name: 'Crimson Text', category: 'serif', source: 'google', isVariable: false, styles: ['Regular', 'Semi Bold', 'Bold'], openTypeFeatures: ['liga', 'kern', 'smcp', 'onum', 'lnum'], popular: false }
];

const OPENTYPE_FEATURE_DESCRIPTIONS = {
    liga: { name: 'Standard Ligatures', category: 'Letterforms', description: 'Common ligatures like fi, fl, ff' },
    rlig: { name: 'Required Ligatures', category: 'Letterforms', description: 'Ligatures required for correct text display' },
    dlig: { name: 'Discretionary Ligatures', category: 'Letterforms', description: 'Rare or decorative ligatures' },
    calt: { name: 'Contextual Alternates', category: 'Letterforms', description: 'Context-dependent character substitutions' },
    ordn: { name: 'Ordinals', category: 'Letterforms', description: 'Superscript for ordinal indicators (1st, 2nd)' },
    ss01: { name: 'Stylistic Set 1', category: 'Stylistic Sets', description: 'Alternate character forms set 1' },
    ss02: { name: 'Stylistic Set 2', category: 'Stylistic Sets', description: 'Alternate character forms set 2' },
    ss03: { name: 'Stylistic Set 3', category: 'Stylistic Sets', description: 'Alternate character forms set 3' },
    ss04: { name: 'Stylistic Set 4', category: 'Stylistic Sets', description: 'Alternate character forms set 4' },
    ss05: { name: 'Stylistic Set 5', category: 'Stylistic Sets', description: 'Alternate character forms set 5' },
    cv01: { name: 'Character Variant 1', category: 'Character Variants', description: 'Alternative glyph variant 1' },
    cv02: { name: 'Character Variant 2', category: 'Character Variants', description: 'Alternative glyph variant 2' },
    cv03: { name: 'Character Variant 3', category: 'Character Variants', description: 'Alternative glyph variant 3' },
    cv04: { name: 'Character Variant 4', category: 'Character Variants', description: 'Alternative glyph variant 4' },
    cv05: { name: 'Character Variant 5', category: 'Character Variants', description: 'Alternative glyph variant 5' },
    cv06: { name: 'Character Variant 6', category: 'Character Variants', description: 'Alternative glyph variant 6' },
    cv07: { name: 'Character Variant 7', category: 'Character Variants', description: 'Alternative glyph variant 7' },
    cv08: { name: 'Character Variant 8', category: 'Character Variants', description: 'Alternative glyph variant 8' },
    cv11: { name: 'Character Variant 11', category: 'Character Variants', description: 'Alternative glyph variant 11' },
    cv14: { name: 'Character Variant 14', category: 'Character Variants', description: 'Alternative glyph variant 14' },
    cv99: { name: 'Character Variant 99', category: 'Character Variants', description: 'Full set of character alternatives' },
    kern: { name: 'Kerning', category: 'Horizontal Spacing', description: 'Adjust spacing between specific character pairs' },
    frac: { name: 'Fractions', category: 'Numbers', description: 'Display fractions in proper typographic form' },
    sups: { name: 'Superscript', category: 'Numbers', description: 'Raise characters above the baseline' },
    subs: { name: 'Subscript', category: 'Numbers', description: 'Lower characters below the baseline' },
    zero: { name: 'Slashed Zero', category: 'Numbers', description: 'Zero with diagonal slash to distinguish from O' },
    onum: { name: 'Oldstyle Figures', category: 'Numbers', description: 'Numbers with varying heights (like lowercase)' },
    lnum: { name: 'Lining Figures', category: 'Numbers', description: 'Numbers aligned to cap height (uppercase style)' },
    smcp: { name: 'Small Capitals', category: 'Letter Case', description: 'Lowercase letters rendered as small capitals' },
    c2sc: { name: 'Capitals to Small Capitals', category: 'Letter Case', description: 'Convert uppercase to small capitals' },
    cpsp: { name: 'Capital Spacing', category: 'Horizontal Spacing', description: 'Optimized spacing for all-caps text' },
    case: { name: 'Case-Sensitive Forms', category: 'Letter Case', description: 'Adjust punctuation for uppercase context' }
};

// ============================================================
// Text Layers (the main data model)
// ============================================================

const TEXT_LAYERS = [
    {
        id: 'tl_001',
        name: 'Page Title',
        content: 'Welcome to the Design System',
        fontFamily: 'Inter',
        fontStyle: 'Bold',
        fontSize: 48,
        lineHeight: { value: 56, unit: 'px' },
        letterSpacing: { value: -0.02, unit: 'em' },
        paragraphSpacing: 0,
        paragraphIndent: 0,
        horizontalAlign: 'left',
        verticalAlign: 'top',
        textDecoration: 'none',
        letterCase: 'none',
        textDirection: 'ltr',
        resizing: 'auto-width',
        truncation: { enabled: false, maxLines: null },
        listStyle: 'none',
        listSpacing: 0,
        hangingPunctuation: false,
        hangingList: false,
        verticalTrim: false,
        links: [],
        openTypeFeatures: { liga: true, calt: true, kern: true },
        textStyleId: 'ts_001',
        variableAxes: {},
        width: null,
        height: null,
        x: 40,
        y: 80,
        locked: false,
        visible: true,
        createdAt: '2026-01-15T09:00:00Z',
        updatedAt: '2026-03-01T14:22:00Z'
    },
    {
        id: 'tl_002',
        name: 'Body Text',
        content: 'Figma is a collaborative design tool that enables teams to create, prototype, and gather feedback in one place. The platform supports real-time collaboration, making it easy for designers, developers, and stakeholders to work together seamlessly.\n\nWith advanced typography controls, you can fine-tune every aspect of your text layers, from font selection and sizing to spacing, alignment, and OpenType features. This ensures your designs maintain typographic consistency across all screens and platforms.',
        fontFamily: 'Inter',
        fontStyle: 'Regular',
        fontSize: 16,
        lineHeight: { value: 150, unit: '%' },
        letterSpacing: { value: 0, unit: 'em' },
        paragraphSpacing: 16,
        paragraphIndent: 0,
        horizontalAlign: 'left',
        verticalAlign: 'top',
        textDecoration: 'none',
        letterCase: 'none',
        textDirection: 'ltr',
        resizing: 'auto-height',
        truncation: { enabled: false, maxLines: null },
        listStyle: 'none',
        listSpacing: 0,
        hangingPunctuation: false,
        hangingList: false,
        verticalTrim: false,
        links: [{ startIndex: 0, endIndex: 5, url: 'https://figma.com', id: 'lnk_001' }],
        openTypeFeatures: { liga: true, calt: true, kern: true },
        textStyleId: 'ts_002',
        variableAxes: {},
        width: 560,
        height: null,
        x: 40,
        y: 160,
        locked: false,
        visible: true,
        createdAt: '2026-01-15T09:05:00Z',
        updatedAt: '2026-03-02T11:30:00Z'
    },
    {
        id: 'tl_003',
        name: 'Section Header',
        content: 'Typography Settings',
        fontFamily: 'Montserrat',
        fontStyle: 'Semi Bold',
        fontSize: 32,
        lineHeight: { value: 40, unit: 'px' },
        letterSpacing: { value: -0.01, unit: 'em' },
        paragraphSpacing: 0,
        paragraphIndent: 0,
        horizontalAlign: 'left',
        verticalAlign: 'top',
        textDecoration: 'none',
        letterCase: 'none',
        textDirection: 'ltr',
        resizing: 'auto-width',
        truncation: { enabled: false, maxLines: null },
        listStyle: 'none',
        listSpacing: 0,
        hangingPunctuation: false,
        hangingList: false,
        verticalTrim: false,
        links: [],
        openTypeFeatures: { liga: true, kern: true, ss01: true },
        textStyleId: 'ts_003',
        variableAxes: { wght: 600 },
        width: null,
        height: null,
        x: 40,
        y: 380,
        locked: false,
        visible: true,
        createdAt: '2026-01-16T10:00:00Z',
        updatedAt: '2026-02-28T16:45:00Z'
    },
    {
        id: 'tl_004',
        name: 'Feature List',
        content: 'Real-time collaboration\nComponent system and variants\nAuto Layout for responsive design\nPrototyping and animations\nDev Mode for handoff\nDesign tokens and variables\nPlugin ecosystem\nFigma Slides presentations',
        fontFamily: 'Inter',
        fontStyle: 'Regular',
        fontSize: 14,
        lineHeight: { value: 24, unit: 'px' },
        letterSpacing: { value: 0, unit: 'em' },
        paragraphSpacing: 0,
        paragraphIndent: 0,
        horizontalAlign: 'left',
        verticalAlign: 'top',
        textDecoration: 'none',
        letterCase: 'none',
        textDirection: 'ltr',
        resizing: 'auto-height',
        truncation: { enabled: false, maxLines: null },
        listStyle: 'bulleted',
        listSpacing: 4,
        hangingPunctuation: false,
        hangingList: true,
        verticalTrim: false,
        links: [],
        openTypeFeatures: { liga: true, calt: true, kern: true },
        textStyleId: null,
        variableAxes: {},
        width: 400,
        height: null,
        x: 40,
        y: 440,
        locked: false,
        visible: true,
        createdAt: '2026-01-20T11:30:00Z',
        updatedAt: '2026-03-01T09:15:00Z'
    },
    {
        id: 'tl_005',
        name: 'Pricing Tiers',
        content: 'Starter - Free forever\nProfessional - $12/editor/month\nOrganization - $45/editor/month\nEnterprise - Custom pricing',
        fontFamily: 'Inter',
        fontStyle: 'Medium',
        fontSize: 14,
        lineHeight: { value: 22, unit: 'px' },
        letterSpacing: { value: 0, unit: 'em' },
        paragraphSpacing: 0,
        paragraphIndent: 0,
        horizontalAlign: 'left',
        verticalAlign: 'top',
        textDecoration: 'none',
        letterCase: 'none',
        textDirection: 'ltr',
        resizing: 'auto-height',
        truncation: { enabled: false, maxLines: null },
        listStyle: 'numbered',
        listSpacing: 2,
        hangingPunctuation: false,
        hangingList: false,
        verticalTrim: false,
        links: [],
        openTypeFeatures: { liga: true, kern: true },
        textStyleId: null,
        variableAxes: {},
        width: 350,
        height: null,
        x: 480,
        y: 440,
        locked: false,
        visible: true,
        createdAt: '2026-01-22T14:00:00Z',
        updatedAt: '2026-02-25T10:30:00Z'
    },
    {
        id: 'tl_006',
        name: 'Call to Action',
        content: 'Get Started for Free',
        fontFamily: 'Poppins',
        fontStyle: 'Semi Bold',
        fontSize: 18,
        lineHeight: { value: 24, unit: 'px' },
        letterSpacing: { value: 0.05, unit: 'em' },
        paragraphSpacing: 0,
        paragraphIndent: 0,
        horizontalAlign: 'center',
        verticalAlign: 'middle',
        textDecoration: 'none',
        letterCase: 'uppercase',
        textDirection: 'ltr',
        resizing: 'fixed',
        truncation: { enabled: false, maxLines: null },
        listStyle: 'none',
        listSpacing: 0,
        hangingPunctuation: false,
        hangingList: false,
        verticalTrim: false,
        links: [{ startIndex: 0, endIndex: 20, url: 'https://figma.com/signup', id: 'lnk_002' }],
        openTypeFeatures: { liga: true, kern: true, cpsp: true },
        textStyleId: 'ts_005',
        variableAxes: {},
        width: 280,
        height: 56,
        x: 40,
        y: 700,
        locked: false,
        visible: true,
        createdAt: '2026-01-25T16:00:00Z',
        updatedAt: '2026-03-03T08:20:00Z'
    },
    {
        id: 'tl_007',
        name: 'Copyright Notice',
        content: '(c) 2026 Figma, Inc. All rights reserved. Terms of Service | Privacy Policy',
        fontFamily: 'Inter',
        fontStyle: 'Regular',
        fontSize: 12,
        lineHeight: { value: 16, unit: 'px' },
        letterSpacing: { value: 0.01, unit: 'em' },
        paragraphSpacing: 0,
        paragraphIndent: 0,
        horizontalAlign: 'center',
        verticalAlign: 'top',
        textDecoration: 'none',
        letterCase: 'none',
        textDirection: 'ltr',
        resizing: 'auto-width',
        truncation: { enabled: false, maxLines: null },
        listStyle: 'none',
        listSpacing: 0,
        hangingPunctuation: false,
        hangingList: false,
        verticalTrim: false,
        links: [
            { startIndex: 42, endIndex: 58, url: 'https://figma.com/tos', id: 'lnk_003' },
            { startIndex: 61, endIndex: 75, url: 'https://figma.com/privacy', id: 'lnk_004' }
        ],
        openTypeFeatures: { liga: true, kern: true },
        textStyleId: 'ts_006',
        variableAxes: {},
        width: null,
        height: null,
        x: 40,
        y: 800,
        locked: false,
        visible: true,
        createdAt: '2026-01-28T12:00:00Z',
        updatedAt: '2026-02-20T15:00:00Z'
    },
    {
        id: 'tl_008',
        name: 'Arabic Welcome',
        content: '\u0645\u0631\u062d\u0628\u0627 \u0628\u0643\u0645 \u0641\u064a \u0646\u0638\u0627\u0645 \u0627\u0644\u062a\u0635\u0645\u064a\u0645',
        fontFamily: 'Noto Sans Arabic',
        fontStyle: 'Bold',
        fontSize: 28,
        lineHeight: { value: 40, unit: 'px' },
        letterSpacing: { value: 0, unit: 'em' },
        paragraphSpacing: 0,
        paragraphIndent: 0,
        horizontalAlign: 'right',
        verticalAlign: 'top',
        textDecoration: 'none',
        letterCase: 'none',
        textDirection: 'rtl',
        resizing: 'auto-width',
        truncation: { enabled: false, maxLines: null },
        listStyle: 'none',
        listSpacing: 0,
        hangingPunctuation: false,
        hangingList: false,
        verticalTrim: false,
        links: [],
        openTypeFeatures: { liga: true, calt: true, kern: true },
        textStyleId: null,
        variableAxes: { wght: 700 },
        width: null,
        height: null,
        x: 600,
        y: 80,
        locked: false,
        visible: true,
        createdAt: '2026-02-01T10:00:00Z',
        updatedAt: '2026-02-28T09:30:00Z'
    },
    {
        id: 'tl_009',
        name: 'Hebrew Body',
        content: '\u05E2\u05D9\u05E6\u05D5\u05D1 \u05D8\u05D9\u05E4\u05D5\u05D2\u05E8\u05E4\u05D9 \u05D4\u05D5\u05D0 \u05D0\u05DE\u05E0\u05D5\u05EA \u05D5\u05DE\u05D3\u05E2 \u05E9\u05DC \u05E1\u05D9\u05D3\u05D5\u05E8 \u05D8\u05E7\u05E1\u05D8',
        fontFamily: 'Noto Sans Hebrew',
        fontStyle: 'Regular',
        fontSize: 16,
        lineHeight: { value: 150, unit: '%' },
        letterSpacing: { value: 0, unit: 'em' },
        paragraphSpacing: 12,
        paragraphIndent: 0,
        horizontalAlign: 'right',
        verticalAlign: 'top',
        textDecoration: 'none',
        letterCase: 'none',
        textDirection: 'rtl',
        resizing: 'auto-height',
        truncation: { enabled: false, maxLines: null },
        listStyle: 'none',
        listSpacing: 0,
        hangingPunctuation: false,
        hangingList: false,
        verticalTrim: false,
        links: [],
        openTypeFeatures: { liga: true, kern: true },
        textStyleId: null,
        variableAxes: {},
        width: 400,
        height: null,
        x: 600,
        y: 140,
        locked: false,
        visible: true,
        createdAt: '2026-02-02T11:00:00Z',
        updatedAt: '2026-02-27T10:15:00Z'
    },
    {
        id: 'tl_010',
        name: 'Japanese Heading',
        content: '\u30C7\u30B6\u30A4\u30F3\u30B7\u30B9\u30C6\u30E0\u306E\u30AC\u30A4\u30C9',
        fontFamily: 'Noto Sans JP',
        fontStyle: 'Bold',
        fontSize: 24,
        lineHeight: { value: 36, unit: 'px' },
        letterSpacing: { value: 0.05, unit: 'em' },
        paragraphSpacing: 0,
        paragraphIndent: 0,
        horizontalAlign: 'left',
        verticalAlign: 'top',
        textDecoration: 'none',
        letterCase: 'none',
        textDirection: 'ltr',
        resizing: 'auto-width',
        truncation: { enabled: false, maxLines: null },
        listStyle: 'none',
        listSpacing: 0,
        hangingPunctuation: false,
        hangingList: false,
        verticalTrim: false,
        links: [],
        openTypeFeatures: { liga: true, kern: true },
        textStyleId: null,
        variableAxes: {},
        width: null,
        height: null,
        x: 600,
        y: 240,
        locked: false,
        visible: true,
        createdAt: '2026-02-05T08:30:00Z',
        updatedAt: '2026-02-26T14:00:00Z'
    },
    {
        id: 'tl_011',
        name: 'Truncated Preview',
        content: 'This is an extremely long text layer that demonstrates the truncation feature in Figma. When text exceeds the available space within a fixed-size bounding box, Figma can display an ellipsis to indicate that additional content exists beyond what is currently visible. This behavior is controlled through the text truncation settings.',
        fontFamily: 'Roboto',
        fontStyle: 'Regular',
        fontSize: 14,
        lineHeight: { value: 20, unit: 'px' },
        letterSpacing: { value: 0, unit: 'em' },
        paragraphSpacing: 0,
        paragraphIndent: 0,
        horizontalAlign: 'left',
        verticalAlign: 'top',
        textDecoration: 'none',
        letterCase: 'none',
        textDirection: 'ltr',
        resizing: 'fixed',
        truncation: { enabled: true, maxLines: 3 },
        listStyle: 'none',
        listSpacing: 0,
        hangingPunctuation: false,
        hangingList: false,
        verticalTrim: false,
        links: [],
        openTypeFeatures: { liga: true, kern: true },
        textStyleId: null,
        variableAxes: { wght: 400, wdth: 100 },
        width: 300,
        height: 64,
        x: 40,
        y: 860,
        locked: false,
        visible: true,
        createdAt: '2026-02-08T09:00:00Z',
        updatedAt: '2026-03-01T11:45:00Z'
    },
    {
        id: 'tl_012',
        name: 'Code Sample',
        content: 'const typography = {\n  fontFamily: "Inter",\n  fontSize: 16,\n  lineHeight: 1.5,\n  letterSpacing: 0\n};',
        fontFamily: 'JetBrains Mono',
        fontStyle: 'Regular',
        fontSize: 13,
        lineHeight: { value: 22, unit: 'px' },
        letterSpacing: { value: 0, unit: 'em' },
        paragraphSpacing: 0,
        paragraphIndent: 0,
        horizontalAlign: 'left',
        verticalAlign: 'top',
        textDecoration: 'none',
        letterCase: 'none',
        textDirection: 'ltr',
        resizing: 'auto-height',
        truncation: { enabled: false, maxLines: null },
        listStyle: 'none',
        listSpacing: 0,
        hangingPunctuation: false,
        hangingList: false,
        verticalTrim: false,
        links: [],
        openTypeFeatures: { liga: true, calt: true, kern: true, zero: true },
        textStyleId: 'ts_007',
        variableAxes: { wght: 400 },
        width: 320,
        height: null,
        x: 600,
        y: 440,
        locked: false,
        visible: true,
        createdAt: '2026-02-10T15:00:00Z',
        updatedAt: '2026-02-28T17:30:00Z'
    },
    {
        id: 'tl_013',
        name: 'Variable Font Demo',
        content: 'Variable fonts allow granular control over weight, width, optical size, and custom axes defined by the font designer.',
        fontFamily: 'Inter',
        fontStyle: 'Regular',
        fontSize: 20,
        lineHeight: { value: 28, unit: 'px' },
        letterSpacing: { value: 0, unit: 'em' },
        paragraphSpacing: 0,
        paragraphIndent: 0,
        horizontalAlign: 'left',
        verticalAlign: 'top',
        textDecoration: 'none',
        letterCase: 'none',
        textDirection: 'ltr',
        resizing: 'auto-height',
        truncation: { enabled: false, maxLines: null },
        listStyle: 'none',
        listSpacing: 0,
        hangingPunctuation: false,
        hangingList: false,
        verticalTrim: true,
        links: [],
        openTypeFeatures: { liga: true, calt: true, kern: true },
        textStyleId: null,
        variableAxes: { wght: 450, slnt: -5 },
        width: 480,
        height: null,
        x: 600,
        y: 600,
        locked: false,
        visible: true,
        createdAt: '2026-02-12T10:30:00Z',
        updatedAt: '2026-03-02T09:00:00Z'
    },
    {
        id: 'tl_014',
        name: 'Strikethrough Example',
        content: 'This text has been marked for deletion and review.',
        fontFamily: 'Inter',
        fontStyle: 'Regular',
        fontSize: 14,
        lineHeight: { value: 20, unit: 'px' },
        letterSpacing: { value: 0, unit: 'em' },
        paragraphSpacing: 0,
        paragraphIndent: 0,
        horizontalAlign: 'left',
        verticalAlign: 'top',
        textDecoration: 'strikethrough',
        letterCase: 'none',
        textDirection: 'ltr',
        resizing: 'auto-width',
        truncation: { enabled: false, maxLines: null },
        listStyle: 'none',
        listSpacing: 0,
        hangingPunctuation: false,
        hangingList: false,
        verticalTrim: false,
        links: [],
        openTypeFeatures: { liga: true, kern: true },
        textStyleId: null,
        variableAxes: {},
        width: null,
        height: null,
        x: 40,
        y: 950,
        locked: false,
        visible: true,
        createdAt: '2026-02-14T13:00:00Z',
        updatedAt: '2026-02-28T14:00:00Z'
    },
    {
        id: 'tl_015',
        name: 'Underlined Link Text',
        content: 'Click here to learn more about advanced typography',
        fontFamily: 'Inter',
        fontStyle: 'Medium',
        fontSize: 14,
        lineHeight: { value: 20, unit: 'px' },
        letterSpacing: { value: 0, unit: 'em' },
        paragraphSpacing: 0,
        paragraphIndent: 0,
        horizontalAlign: 'left',
        verticalAlign: 'top',
        textDecoration: 'underline',
        letterCase: 'none',
        textDirection: 'ltr',
        resizing: 'auto-width',
        truncation: { enabled: false, maxLines: null },
        listStyle: 'none',
        listSpacing: 0,
        hangingPunctuation: false,
        hangingList: false,
        verticalTrim: false,
        links: [{ startIndex: 0, endIndex: 49, url: 'https://help.figma.com/typography', id: 'lnk_005' }],
        openTypeFeatures: { liga: true, kern: true },
        textStyleId: null,
        variableAxes: {},
        width: null,
        height: null,
        x: 40,
        y: 990,
        locked: false,
        visible: true,
        createdAt: '2026-02-15T09:30:00Z',
        updatedAt: '2026-03-01T10:00:00Z'
    },
    {
        id: 'tl_016',
        name: 'Indented Quote',
        content: '"Good typography is invisible. Bad typography is everywhere."\n- Erik Spiekermann',
        fontFamily: 'Playfair Display',
        fontStyle: 'Regular',
        fontSize: 22,
        lineHeight: { value: 32, unit: 'px' },
        letterSpacing: { value: 0, unit: 'em' },
        paragraphSpacing: 8,
        paragraphIndent: 24,
        horizontalAlign: 'left',
        verticalAlign: 'top',
        textDecoration: 'none',
        letterCase: 'none',
        textDirection: 'ltr',
        resizing: 'auto-height',
        truncation: { enabled: false, maxLines: null },
        listStyle: 'none',
        listSpacing: 0,
        hangingPunctuation: true,
        hangingList: false,
        verticalTrim: false,
        links: [],
        openTypeFeatures: { liga: true, kern: true, ss01: true },
        textStyleId: null,
        variableAxes: { wght: 400 },
        width: 480,
        height: null,
        x: 600,
        y: 700,
        locked: false,
        visible: true,
        createdAt: '2026-02-18T11:00:00Z',
        updatedAt: '2026-03-01T16:30:00Z'
    },
    {
        id: 'tl_017',
        name: 'Small Caps Header',
        content: 'Design Principles',
        fontFamily: 'Montserrat',
        fontStyle: 'Medium',
        fontSize: 14,
        lineHeight: { value: 20, unit: 'px' },
        letterSpacing: { value: 0.1, unit: 'em' },
        paragraphSpacing: 0,
        paragraphIndent: 0,
        horizontalAlign: 'left',
        verticalAlign: 'top',
        textDecoration: 'none',
        letterCase: 'small-caps',
        textDirection: 'ltr',
        resizing: 'auto-width',
        truncation: { enabled: false, maxLines: null },
        listStyle: 'none',
        listSpacing: 0,
        hangingPunctuation: false,
        hangingList: false,
        verticalTrim: false,
        links: [],
        openTypeFeatures: { liga: true, kern: true, smcp: true, cpsp: true },
        textStyleId: 'ts_008',
        variableAxes: { wght: 500 },
        width: null,
        height: null,
        x: 40,
        y: 1040,
        locked: false,
        visible: true,
        createdAt: '2026-02-20T14:00:00Z',
        updatedAt: '2026-03-02T13:00:00Z'
    },
    {
        id: 'tl_018',
        name: 'Mixed Direction Text',
        content: 'The Arabic word \u0645\u0631\u062d\u0628\u0627 means "hello" in English.',
        fontFamily: 'Inter',
        fontStyle: 'Regular',
        fontSize: 16,
        lineHeight: { value: 24, unit: 'px' },
        letterSpacing: { value: 0, unit: 'em' },
        paragraphSpacing: 0,
        paragraphIndent: 0,
        horizontalAlign: 'left',
        verticalAlign: 'top',
        textDecoration: 'none',
        letterCase: 'none',
        textDirection: 'ltr',
        resizing: 'auto-width',
        truncation: { enabled: false, maxLines: null },
        listStyle: 'none',
        listSpacing: 0,
        hangingPunctuation: false,
        hangingList: false,
        verticalTrim: false,
        links: [],
        openTypeFeatures: { liga: true, kern: true },
        textStyleId: null,
        variableAxes: {},
        width: null,
        height: null,
        x: 600,
        y: 300,
        locked: false,
        visible: true,
        createdAt: '2026-02-22T09:00:00Z',
        updatedAt: '2026-02-28T11:00:00Z'
    },
    {
        id: 'tl_019',
        name: 'Release Notes Header',
        content: 'What\'s New in v4.2',
        fontFamily: 'DM Sans',
        fontStyle: 'Bold',
        fontSize: 36,
        lineHeight: { value: 44, unit: 'px' },
        letterSpacing: { value: -0.02, unit: 'em' },
        paragraphSpacing: 0,
        paragraphIndent: 0,
        horizontalAlign: 'left',
        verticalAlign: 'top',
        textDecoration: 'none',
        letterCase: 'none',
        textDirection: 'ltr',
        resizing: 'auto-width',
        truncation: { enabled: false, maxLines: null },
        listStyle: 'none',
        listSpacing: 0,
        hangingPunctuation: false,
        hangingList: false,
        verticalTrim: true,
        links: [],
        openTypeFeatures: { liga: true, kern: true },
        textStyleId: null,
        variableAxes: { wght: 700, opsz: 36 },
        width: null,
        height: null,
        x: 40,
        y: 1100,
        locked: false,
        visible: true,
        createdAt: '2026-02-24T10:30:00Z',
        updatedAt: '2026-03-03T09:00:00Z'
    },
    {
        id: 'tl_020',
        name: 'Step Instructions',
        content: 'Install the font file on your system\nOpen Figma and select the text tool\nChoose your font from the font picker\nAdjust size, weight, and spacing\nApply OpenType features as needed\nCreate a text style for reuse',
        fontFamily: 'Inter',
        fontStyle: 'Regular',
        fontSize: 14,
        lineHeight: { value: 22, unit: 'px' },
        letterSpacing: { value: 0, unit: 'em' },
        paragraphSpacing: 0,
        paragraphIndent: 0,
        horizontalAlign: 'left',
        verticalAlign: 'top',
        textDecoration: 'none',
        letterCase: 'none',
        textDirection: 'ltr',
        resizing: 'auto-height',
        truncation: { enabled: false, maxLines: null },
        listStyle: 'numbered',
        listSpacing: 6,
        hangingPunctuation: false,
        hangingList: false,
        verticalTrim: false,
        links: [],
        openTypeFeatures: { liga: true, kern: true },
        textStyleId: null,
        variableAxes: {},
        width: 380,
        height: null,
        x: 600,
        y: 800,
        locked: false,
        visible: true,
        createdAt: '2026-02-25T13:00:00Z',
        updatedAt: '2026-03-02T14:30:00Z'
    }
];

// ============================================================
// Text Styles
// ============================================================

const TEXT_STYLES = [
    { id: 'ts_001', name: 'Heading/H1', fontFamily: 'Inter', fontStyle: 'Bold', fontSize: 48, lineHeight: { value: 56, unit: 'px' }, letterSpacing: { value: -0.02, unit: 'em' }, paragraphSpacing: 0, paragraphIndent: 0, textDecoration: 'none', letterCase: 'none', listStyle: 'none', openTypeFeatures: { liga: true, calt: true, kern: true }, description: 'Primary page heading', createdAt: '2026-01-10T09:00:00Z', updatedAt: '2026-02-28T10:00:00Z' },
    { id: 'ts_002', name: 'Body/Regular', fontFamily: 'Inter', fontStyle: 'Regular', fontSize: 16, lineHeight: { value: 150, unit: '%' }, letterSpacing: { value: 0, unit: 'em' }, paragraphSpacing: 16, paragraphIndent: 0, textDecoration: 'none', letterCase: 'none', listStyle: 'none', openTypeFeatures: { liga: true, calt: true, kern: true }, description: 'Default body text', createdAt: '2026-01-10T09:05:00Z', updatedAt: '2026-02-28T10:05:00Z' },
    { id: 'ts_003', name: 'Heading/H2', fontFamily: 'Montserrat', fontStyle: 'Semi Bold', fontSize: 32, lineHeight: { value: 40, unit: 'px' }, letterSpacing: { value: -0.01, unit: 'em' }, paragraphSpacing: 0, paragraphIndent: 0, textDecoration: 'none', letterCase: 'none', listStyle: 'none', openTypeFeatures: { liga: true, kern: true, ss01: true }, description: 'Section heading', createdAt: '2026-01-10T09:10:00Z', updatedAt: '2026-02-28T10:10:00Z' },
    { id: 'ts_004', name: 'Heading/H3', fontFamily: 'Inter', fontStyle: 'Semi Bold', fontSize: 24, lineHeight: { value: 32, unit: 'px' }, letterSpacing: { value: -0.01, unit: 'em' }, paragraphSpacing: 0, paragraphIndent: 0, textDecoration: 'none', letterCase: 'none', listStyle: 'none', openTypeFeatures: { liga: true, kern: true }, description: 'Subsection heading', createdAt: '2026-01-10T09:15:00Z', updatedAt: '2026-02-28T10:15:00Z' },
    { id: 'ts_005', name: 'Button/Primary', fontFamily: 'Poppins', fontStyle: 'Semi Bold', fontSize: 18, lineHeight: { value: 24, unit: 'px' }, letterSpacing: { value: 0.05, unit: 'em' }, paragraphSpacing: 0, paragraphIndent: 0, textDecoration: 'none', letterCase: 'uppercase', listStyle: 'none', openTypeFeatures: { liga: true, kern: true, cpsp: true }, description: 'Primary button text', createdAt: '2026-01-12T11:00:00Z', updatedAt: '2026-02-20T15:00:00Z' },
    { id: 'ts_006', name: 'Caption/Small', fontFamily: 'Inter', fontStyle: 'Regular', fontSize: 12, lineHeight: { value: 16, unit: 'px' }, letterSpacing: { value: 0.01, unit: 'em' }, paragraphSpacing: 0, paragraphIndent: 0, textDecoration: 'none', letterCase: 'none', listStyle: 'none', openTypeFeatures: { liga: true, kern: true }, description: 'Small captions and footnotes', createdAt: '2026-01-12T11:30:00Z', updatedAt: '2026-02-20T15:30:00Z' },
    { id: 'ts_007', name: 'Code/Inline', fontFamily: 'JetBrains Mono', fontStyle: 'Regular', fontSize: 13, lineHeight: { value: 22, unit: 'px' }, letterSpacing: { value: 0, unit: 'em' }, paragraphSpacing: 0, paragraphIndent: 0, textDecoration: 'none', letterCase: 'none', listStyle: 'none', openTypeFeatures: { liga: true, calt: true, kern: true, zero: true }, description: 'Code snippets and inline code', createdAt: '2026-01-14T14:00:00Z', updatedAt: '2026-02-25T10:00:00Z' },
    { id: 'ts_008', name: 'Label/SmallCaps', fontFamily: 'Montserrat', fontStyle: 'Medium', fontSize: 14, lineHeight: { value: 20, unit: 'px' }, letterSpacing: { value: 0.1, unit: 'em' }, paragraphSpacing: 0, paragraphIndent: 0, textDecoration: 'none', letterCase: 'small-caps', listStyle: 'none', openTypeFeatures: { liga: true, kern: true, smcp: true, cpsp: true }, description: 'Small caps label for section dividers', createdAt: '2026-01-18T09:00:00Z', updatedAt: '2026-02-22T12:00:00Z' },
    { id: 'ts_009', name: 'Body/Large', fontFamily: 'Inter', fontStyle: 'Regular', fontSize: 18, lineHeight: { value: 28, unit: 'px' }, letterSpacing: { value: 0, unit: 'em' }, paragraphSpacing: 20, paragraphIndent: 0, textDecoration: 'none', letterCase: 'none', listStyle: 'none', openTypeFeatures: { liga: true, calt: true, kern: true }, description: 'Large body for introductory paragraphs', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-02-26T14:00:00Z' },
    { id: 'ts_010', name: 'Heading/Display', fontFamily: 'Playfair Display', fontStyle: 'Bold', fontSize: 64, lineHeight: { value: 72, unit: 'px' }, letterSpacing: { value: -0.03, unit: 'em' }, paragraphSpacing: 0, paragraphIndent: 0, textDecoration: 'none', letterCase: 'none', listStyle: 'none', openTypeFeatures: { liga: true, kern: true, ss01: true }, description: 'Display heading for hero sections', createdAt: '2026-01-22T09:30:00Z', updatedAt: '2026-02-28T11:00:00Z' },
    { id: 'ts_011', name: 'Body/Small', fontFamily: 'Inter', fontStyle: 'Regular', fontSize: 13, lineHeight: { value: 18, unit: 'px' }, letterSpacing: { value: 0, unit: 'em' }, paragraphSpacing: 10, paragraphIndent: 0, textDecoration: 'none', letterCase: 'none', listStyle: 'none', openTypeFeatures: { liga: true, kern: true }, description: 'Compact body text for dense layouts', createdAt: '2026-01-24T16:00:00Z', updatedAt: '2026-02-24T09:00:00Z' },
    { id: 'ts_012', name: 'Label/Overline', fontFamily: 'Inter', fontStyle: 'Semi Bold', fontSize: 11, lineHeight: { value: 16, unit: 'px' }, letterSpacing: { value: 0.08, unit: 'em' }, paragraphSpacing: 0, paragraphIndent: 0, textDecoration: 'none', letterCase: 'uppercase', listStyle: 'none', openTypeFeatures: { liga: true, kern: true }, description: 'Overline label for categories', createdAt: '2026-01-26T10:30:00Z', updatedAt: '2026-02-22T14:00:00Z' }
];

// ============================================================
// Preferences / Settings
// ============================================================

const PREFERENCES = {
    smartQuotes: true,
    smartSymbols: true,
    defaultFontFamily: 'Inter',
    defaultFontStyle: 'Regular',
    defaultFontSize: 16,
    defaultLineHeight: { value: 150, unit: '%' },
    defaultLetterSpacing: { value: 0, unit: 'em' },
    defaultHorizontalAlign: 'left',
    defaultTextDirection: 'ltr',
    showFontPreview: true,
    recentFonts: ['Inter', 'Roboto', 'Montserrat', 'Poppins', 'Playfair Display'],
    fontFilter: 'all',
    snapToGrid: true,
    nudgeAmount: 1,
    bigNudgeAmount: 10,
    spellingLanguage: 'English (US)'
};

const SPELLING_LANGUAGES = [
    'English (US)', 'English (UK)', 'French', 'German', 'Spanish', 'Italian',
    'Portuguese (BR)', 'Portuguese (PT)', 'Dutch', 'Swedish', 'Norwegian',
    'Danish', 'Finnish', 'Polish', 'Czech', 'Romanian', 'Turkish', 'Japanese',
    'Korean', 'Simplified Chinese', 'Traditional Chinese', 'Arabic', 'Hebrew'
];

const FONT_SIZE_PRESETS = [8, 9, 10, 11, 12, 13, 14, 16, 18, 20, 24, 28, 32, 36, 40, 48, 56, 64, 72, 80, 96, 128];

const LINE_HEIGHT_UNITS = ['px', '%'];

const LETTER_SPACING_UNITS = ['px', 'em', '%'];

const HORIZONTAL_ALIGNMENTS = ['left', 'center', 'right', 'justify'];

const VERTICAL_ALIGNMENTS = ['top', 'middle', 'bottom'];

const TEXT_DECORATIONS = ['none', 'underline', 'strikethrough'];

const LETTER_CASES = ['none', 'uppercase', 'lowercase', 'capitalize', 'small-caps'];

const TEXT_DIRECTIONS = ['ltr', 'rtl'];

const RESIZING_MODES = ['auto-width', 'auto-height', 'fixed'];

const LIST_STYLES = ['none', 'bulleted', 'numbered'];

const FONT_FILTERS = [
    { id: 'all', label: 'All fonts' },
    { id: 'in-file', label: 'In this file' },
    { id: 'popular', label: 'Popular' },
    { id: 'organization', label: 'Used at Acme Corp' },
    { id: 'installed', label: 'Installed by you' },
    { id: 'google', label: 'Google fonts' },
    { id: 'variable', label: 'Variable fonts' }
];

// ============================================================
// Smart Symbols mapping
// ============================================================

const SMART_SYMBOLS = [
    { input: '->', output: '\u2192', name: 'Right Arrow' },
    { input: '<-', output: '\u2190', name: 'Left Arrow' },
    { input: 'vv', output: '\u2193', name: 'Down Arrow' },
    { input: '^^', output: '\u2191', name: 'Up Arrow' },
    { input: '(c)', output: '\u00A9', name: 'Copyright' },
    { input: '(r)', output: '\u00AE', name: 'Registered' },
    { input: '(tm)', output: '\u2122', name: 'Trademark' },
    { input: '[ ]', output: '\u25A2', name: 'Checkbox' },
    { input: '...', output: '\u2026', name: 'Ellipsis' },
    { input: '--', output: '\u2014', name: 'Em Dash' },
    { input: '1/2', output: '\u00BD', name: 'Half' },
    { input: '1/4', output: '\u00BC', name: 'Quarter' },
    { input: '3/4', output: '\u00BE', name: 'Three Quarters' }
];

// ============================================================
// File/Project metadata
// ============================================================

const FILE_INFO = {
    id: 'file_001',
    name: 'Design System v4.2',
    projectName: 'Product Design',
    teamName: 'Acme Corp Design Team',
    lastModified: '2026-03-03T09:15:00Z',
    createdAt: '2026-01-10T08:00:00Z',
    pageCount: 5,
    currentPage: 'Typography',
    pages: [
        { id: 'pg_001', name: 'Cover' },
        { id: 'pg_002', name: 'Typography' },
        { id: 'pg_003', name: 'Colors' },
        { id: 'pg_004', name: 'Components' },
        { id: 'pg_005', name: 'Layouts' }
    ]
};

const CURRENT_USER = {
    id: 'usr_f4e8a1c2',
    name: 'Sarah Chen',
    email: 'sarah.chen@acme.io',
    avatarColor: '#7B61FF',
    role: 'Editor',
    plan: 'Organization'
};
